# Generated by Django 3.0.7 on 2020-08-24 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallOfRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='call of roll date')),
                ('cursus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Cursus')),
            ],
        ),
        migrations.CreateModel(
            name='CallOfRoll_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAbsent', models.BooleanField(default=False)),
                ('reason', models.CharField(default='Unknown', max_length=255, null=True)),
                ('absentDate', models.DateField(verbose_name='When was he absent')),
                ('callofroll', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.CallOfRoll')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Student')),
            ],
        ),
    ]
