# Generated by Django 3.0.7 on 2020-08-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_auto_20200826_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='isParticular',
            field=models.BooleanField(default=False),
        ),
    ]
