# Generated by Django 3.0.7 on 2020-08-28 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0005_auto_20200826_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='call of roll date')),
                ('cursus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Cursus')),
            ],
        ),
        migrations.AddField(
            model_name='presence',
            name='appel_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Appel_list'),
        ),
    ]
